services:
  postgis_db:
    image: postgis/postgis:15-3.3
    container_name: gtfs_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGISUSER}
      POSTGRES_DB: ${POSTGISDBNAME}
      POSTGRES_PASSWORD: ${POSTGISPASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgis_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGEMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD}
    ports:
      - 80:80
    depends_on:
      - postgis_db

  tileserver:
    image: maptiler/tileserver-gl
    container_name: tileserver
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./tileserver-guatemala:/data
