# Base de datos PostGIS para GTFS
services:
  db_postgis:
    image: postgis/postgis:15-3.4
    container_name: gtfs_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGISUSER}
      POSTGRES_DB: ${POSTGISDBNAME}
      POSTGRES_PASSWORD: ${POSTGISPASSWORD}
      TZ: America/Guatemala
    ports:
      - 5432:5432
    volumes:
      - ./postgis_data:/var/lib/postgresql/data

  # use pgadmin to manage the database
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGEMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD}
    ports:
      - 80:80
    depends_on:
      - db_postgis

  # tile server for rendering maps
  tileserver:
    image: maptiler/tileserver-gl
    container_name: tile_server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./tileserver-guatemala:/data
